dir=$(dirname $0)
version="$1"
release="$2"

shift 2
$dir/install-packages-from-koji.sh    p=qemu,v=$version,r=$release \
	rpm=qemu-{audio-{alsa,dbus,jack,oss,pa,sdl,spice},block-{blkio,curl,dmg,gluster,iscsi,nfs,rbd,ssh},char-{baum,spice},common,device-display-{qxl,vhost-user-gpu,virtio-gpu{,-cccw,-gl,-pci,-pci-gl},virtio-vga{,-gl}},device-usb-{host,redirect,smartcard},img,kvm,pr-helper,system-{aarch64,alpha,arm,avr,cris,loongarch64,m68k,microblaze,mips,nios2,or1k,ppc,riscv,rx,s390x,sh4,sparc,tricore,x86,xtensa}{,-core},tools,ui-{curses,egl-headless,gtk,opengl,sdl,spice-app,spice-core},user,user-static,user-static-{aarch64,alpha,arm,cris,hexagon,hppa,loongarch64,m68k,microblaze,mips,nios2,or1k,ppc,riscv,s390x,sh4,sparc,x86,xtensa}} \
    "$@"

#qemu-virtiofsd

# qemu
# qemu-audio-alsa
# qemu-audio-dbus
# qemu-audio-jack
# qemu-audio-oss
# qemu-audio-pa
# qemu-audio-sdl
# qemu-audio-spice
# qemu-block-blkio
# qemu-block-curl
# qemu-block-dmg
# qemu-block-gluster
# qemu-block-iscsi
# qemu-block-nfs
# qemu-block-rbd
# qemu-block-ssh
# qemu-char-baum
# qemu-char-spice
# qemu-common
# qemu-device-display-qxl
# qemu-device-display-vhost-user-gpu
# qemu-device-display-virtio-gpu
# qemu-device-display-virtio-gpu-ccw
# qemu-device-display-virtio-gpu-gl
# qemu-device-display-virtio-gpu-pci
# qemu-device-display-virtio-gpu-pci-gl
# qemu-device-display-virtio-vga
# qemu-device-display-virtio-vga-gl
# qemu-device-usb-host
# qemu-device-usb-redirect
# qemu-device-usb-smartcard
## qemu-docs
## qemu-guest-agent
# qemu-img
# qemu-kvm
# qemu-kvm-core
# qemu-pr-helper
# qemu-system-aarch64
# qemu-system-aarch64-core
# qemu-system-alpha
# qemu-system-alpha-core
# qemu-system-arm
# qemu-system-arm-core
# qemu-system-avr
# qemu-system-avr-core
# qemu-system-cris
# qemu-system-cris-core
# qemu-system-hppa
# qemu-system-hppa-core
# qemu-system-loongarch64
# qemu-system-loongarch64-core
# qemu-system-m68k
# qemu-system-m68k-core
# qemu-system-microblaze
# qemu-system-microblaze-core
# qemu-system-mips
# qemu-system-mips-core
# qemu-system-nios2
# qemu-system-nios2-core
# qemu-system-or1k
# qemu-system-or1k-core
# qemu-system-ppc
# qemu-system-ppc-core
# qemu-system-riscv
# qemu-system-riscv-core
# qemu-system-rx
# qemu-system-rx-core
# qemu-system-s390x
# qemu-system-s390x-core
# qemu-system-sh4
# qemu-system-sh4-core
# qemu-system-sparc
# qemu-system-sparc-core
# qemu-system-tricore
# qemu-system-tricore-core
# qemu-system-x86
# qemu-system-x86-core
# qemu-system-xtensa
# qemu-system-xtensa-core
## qemu-tests
# qemu-tools
# qemu-ui-curses
## qemu-ui-dbus
# qemu-ui-egl-headless
# qemu-ui-gtk
# qemu-ui-opengl
# qemu-ui-sdl
# qemu-ui-spice-app
# qemu-ui-spice-core
# qemu-user
## qemu-user-binfmt
# qemu-user-static
# qemu-user-static-aarch64
# qemu-user-static-alpha
# qemu-user-static-arm
# qemu-user-static-cris
# qemu-user-static-hexagon
# qemu-user-static-hppa
# qemu-user-static-loongarch64
# qemu-user-static-m68k
# qemu-user-static-microblaze
# qemu-user-static-mips
# qemu-user-static-nios2
# qemu-user-static-or1k
# qemu-user-static-ppc
# qemu-user-static-riscv
# qemu-user-static-s390x
# qemu-user-static-sh4
# qemu-user-static-sparc
# qemu-user-static-x86
# qemu-user-static-xtensa
